# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'Demo' do
  pod 'PGDatePicker', '>= 1.5.4'
  pod 'Reveal-SDK', '~> 10’, :configurations => ['Debug’]
end
